### ISSUE TITLE
Windows build hitting a snag

### ISSUE THREAD

**Issue by drwbns** [gfaster/clod#1]
Hey Gavin. This work you did is really awesome but I'm using Visual Studio on a Windows machine and it has been a pain to build. I finally was able to build and run it but I am hitting a weird access violation. Any ideas? Also, does it use some custom library versions of GKlib or Metis? Thanks for any help!

![image](https://github.com/gfaster/clod/assets/719541/e6123b0f-0a69-4ad5-af0b-ca392e2522c1)

**Comment by drwbns** [comment]
I got it working after changing lines in gk error.c file. Lines 22-24 need to change to:

__declspec(thread) int gk_cur_jbufs=-1;
__declspec(thread) jmp_buf gk_jbufs[MAX_JBUFS];
__declspec(thread) jmp_buf gk_jbuf;

Same sort of changes in gk_externs.h - 

#ifndef _GK_ERROR_C_
/* declared in error.c */
__declspec(thread) int gk_cur_jbufs;
__declspec(thread) jmp_buf gk_jbufs[];
__declspec(thread) jmp_buf gk_jbuf;

#endif

Also had to add /FORCE:Multiple to the linker

**Comment by gfaster** [comment]
This repository doesn't use a patched build of METIS or GKLib, but there are configure flags that can create differences on different platforms. 

I don't use Windows anymore so I hadn't tried building it there, but the bug you encountered looks like it is a bug in METIS that [has open pull requests](https://github.com/KarypisLab/METIS/pull/74)

**Comment by drwbns** [comment]
Ah ok. I will check that out. I got it running properly in Windows using a 64-bit configuration but it is giving me some sort of vector out of range exception when the rabbit model is moved to the very far extent so the program crashes at that point. I haven't spent too much time to figure that error out yet but I'll open a new issue if I can't figure it out. Thanks!
